server:
  port: 8081
app:
  jwtSecret: asdfghjklpoiuytrewqzxcvbnmqazwsxedcrfvtgbyh
  jwtExpirationMs: 86400000
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/thebagsdb
    username: approot
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: changepasassword
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: changeemail